import type { Metadata } from "next";
import { CartProvider } from "./context/cart-context";
import NavBar from "@/components/nav-bar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <html lang="en">
        <body>
          <main>
            <NavBar />
              {children}
          </main>
        </body>
      </html>
    </CartProvider>
  );
}